name: bitcoin_bip44
version: 0.1.2
description: Library implementing Bitcoins BIP44 (HD wallet organization) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  pointycastle:
    git:
      url: https://github.com/jungsoo827/pointycastle.git
      ref: v1.0.2
  bitcoin_bip32:
    git:
      url: https://github.com/jungsoo827/bitcoin_bip32
      ref: v0.1.3
  bech32: ^0.1.2
  http: ^0.12.0+2

dev_dependencies:
#  pointycastle:
#    path: ../pointycastle-jungsoo827
#  bitcoin_bip32:
#    path: ../bitcoin_bip32
  test: ^1.9.3
  hex: ^0.1.2
  mock_web_server:
    git:
      url: git://github.com/haarts/MockWebServer.git
      ref: f8079e9f52ac45d920c677e545316a6905eaf819



